#!/bin/sh

trap "read -t5 -p 'Init exited. Press any key to continue...' -n1" EXIT
set -e

mount -t proc proc /proc
mount -t sysfs proc /sys
mount -n -t devtmpfs devtmpfs /dev
mount -n -t cgroup2 cgroup2 /sys/fs/cgroup

echo "VM init finished."
exec /controller
