[package]
name = "controller"
version = "0.1.0"
edition = "2021"
authors = ["Matteo Bertucci"]

[features]
skipselftests = []

[dependencies]
exec = "0.3.1"
pty = "0.2.2"
fuser = "0.11.0"
libc = "0.2.121"