#!/bin/sh
# Initialization file ran by the kernel to set up the environment

trap "echo 'Init exited. Press any key to continue to kernel panic.' && read -t10 -n1" EXIT
set -e

mount -t proc proc /proc
mount -t sysfs proc /sys
mount -n -t devtmpfs devtmpfs /dev
mount -n -t cgroup2 cgroup2 /sys/fs/cgroup
mkdir /dev/pts
mount -n -t devpts devpts /dev/pts

ifconfig lo up
ifconfig eth0 10.0.2.15 up
ip route add 10.0.2.0/24 dev eth0
route add default gw 10.0.2.2 eth0

echo "VM initialization finished."

for i in "$@"; do
  case $i in
    binary=*)
      exec "${i#*=}"
      shift
      ;;
    *)
      ;;
  esac
done

RUST_BACKTRACE=1 /controller $@
